### ISSUE TITLE
STA9750 cndy17 Mini Project 0 

### ISSUE THREAD

**Issue by cndy17** [cndy17/STA9750-2024-FALL#1]
Hi @michaelweylandt!

I've created my STA9750 website - check it out!

https://cndy17.github.io/STA9750-2024-FALL

**Comment by michaelweylandt** [comment]
Thanks @cndy17 !

Peer Feedback:

- @velasco23
- @bleuuuz
- @Malexandra-Jerez

Please a look at the website associated with this GitHub repo
and provide some peer feedback to @cndy17.

Website URL should be: https://cndy17.github.io/STA9750-2024-FALL/

If that link doesn't work, please check out the GitHub profile for @cndy17 and
see if you can help them get it working.

At a minimum, please note:

1. Something you like about the submission.
2. A suggestion on how to improve it.

Feel free to link to other repos, the course documentation, or other useful
examples.

This submission is ungraded, so there's you don't need to provide
a numerical score.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by bleuuuz** [comment]
Hi Cindy! Thanks for sharing! I think the "little about me" section is a great addition because it gives your website a more human aspect to it and shows you're passionate about many things! Maybe you can add what you're hoping to accomplish in the future with the new skills you're learning. (The salsa and bachata are pretty cool)

**Comment by velasco23** [comment]
Hi @cndy17 , I liked the formatting of your website. It made the website very easy to read and aesthetically pleasing.

**Comment by Malexandra-Jerez** [comment]
Hi @cndy17 <https://github.com/cndy17>!

Great website! Your Bio and picture, it all works out perfectly. This is
also very professional.

A suggestion - truthful nothing. In fact, this helped me to make one
similar to yours.

Kindly,
Maria Alexandra Jerez
